### ISSUE TITLE
Шрифт "Адрес" в карточке информации о парковке выполнен в цвете #191C30

### ISSUE THREAD

**Issue by KateSibi** [car-parking-tracking/Bug-Report#1]
**id:** BUG-1
**Серьёзность бага:** Trivial
**Приоритет:** Low

**Предусловие:** Запустить приложение Parkonaft

**Шаги:** 

1 Открыть консоль разработчика
> (Windows: Ctrl+Shift+I; MacOS: Command+Option+I)

2 Открыть вкладку Элементы
3 На карте нажмите на значок "Парковка" 
4 В открывшейся карточке выберите строку "Адрес"

**Фактический результат:** Шрифт "Адрес" в карточке информации о парковке выполнен в цвете #191C30  
**Ожидаемый результат:** Шрифт "Адрес" в карточке информации о парковке выполнен в цвете #878787

**Окружение:**
1. ОС: Windows 10 Pro (версия 22H2) Браузер: Google Chrome Версия: 116.0.5845.97 (64 бит) Разрешение 1920х1080
2. ОС: MacOS Monterey (версия 12.6.8) Браузер: Safari (версия 16.6) Разрешение 1920х1080

**Comment by shinonhorror** [comment]
Выполнено
