### ISSUE TITLE
Текст внутри выпадающего списка строки поиска имеет размер 16px

### ISSUE THREAD

**Issue by KateSibi** [car-parking-tracking/Bug-Report#2]
**id**: BUG-2
**Серьёзность бага:** Trivial
**Приоритет:** Low

**Предусловие:** Запустить приложение Parkonaft

**Шаги:** 

1 Открыть консоль разработчика 
> (Windows: Ctrl+Shift+I; MacOS: Command+Option+I)

2 Открыть вкладку Elements
3 В строке поиска ввести валидное значение (Москва)
4 Нажать на стрелку в левом верхнем углу
5 Выбрать исследуемый элемент на странице (текст внутри выпадающего списка строки)

**ФР:** Текст внутри выпадающего списка строки поиска имеет размер 16px
**ОР:** Текст внутри выпадающего списка строки поиска имеет размер 24px

**Окружение:**

**Окружение:** 
1. ОС: Windows 10 Pro (версия 22H2) Браузер: Google Chrome Версия: 116.0.5845.97 (64 бит) Разрешение 1920х1080
2. ОС: Windows 10 Pro (версия 22H2) Браузер: Яндекс.Браузер Версия: 23.7.1.1140 (64-bit) Разрешение 1920х1080 
3. ОС: MacOS Monterey (версия 12.6.8) Браузер: Safari (версия 16.6) Разрешение 1920х1080

![image](https://github.com/car-parking-tracking/Bug-Report/assets/117051965/d3540533-45a5-485c-8fcf-5ba2b27dec62)

**Comment by shinonhorror** [comment]
Выполнено
